# -*- coding: utf-8 -*-
"""augFunctio1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1P9Kx--CaIcPzgD8Fgk3nlkJnmFmuxTX-
"""
import matplotlib.pyplot as plt
import matplotlib.image as mpimg

from glob import glob
from pathlib import Path

import albumentations as A
import cv2
import random
import time
import matplotlib

def Aug2Image(pathOne,pathTwo):
  image = cv2.imread(pathOne)
  mask = cv2.imread(pathTwo)
  transform = A.Compose([
    A.RandomCrop(width=256, height=256),
    A.HorizontalFlip(p=random.uniform(0, 0.8)),
    A.RandomBrightnessContrast(p=random.uniform(0, 1)),
    #A.RandomScale(0.5)
    A.ShiftScaleRotate()])
  transformed = transform(image=image, mask=mask)
  transformed_image = transformed['image']
  transformed_mask = transformed['mask']
  t = int(time.time())
  mpimg.imsave(pathOne[:-4]+str(format(t))+'.png',transformed_image)
  mpimg.imsave(pathTwo[:-4]+str(format(t))+'.png',transformed_mask)



import os

root_folder = "/"
os.makedirs(root_folder, exist_ok=True)
image_paths = glob("/scratch/users/hariri/Seg_Dataset1/Org/*.png")
mask_paths = glob("/scratch1/users/hariri/Seg_Dataset1/Seg/*.png")
image_paths.sort()
mask_paths.sort()
for i in range(len(image_paths)):
  for x in range(3):
    Aug2Image(image_paths[i],mask_paths[i])

root_folder = "/"
os.makedirs(root_folder, exist_ok=True)
test_paths = glob("/scratch/users/hariri/Test_Dataset1/Org/*.png")
test_mask_paths = glob("/scratch1/users/hariri/Test_Dataset1/Seg/*.png")
test_paths.sort()
test_mask_paths.sort()
for i in range(len(test_paths)):
  for x in range(3):
    Aug2Image(test_paths[i],test_mask_paths[i])
